# Generated by Django 4.2.7 on 2023-11-15 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_uploadedzip_delete_processedfolder'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedzip',
            name='filename',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='uploadedzip',
            name='rules',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='uploadedzip',
            name='vulnerablity',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
