# Generated by Django 4.2.7 on 2023-11-15 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_uploadedzip_filename_uploadedzip_rules_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadedzip',
            name='rules',
        ),
        migrations.RemoveField(
            model_name='uploadedzip',
            name='vulnerablity',
        ),
    ]
