# Generated by Django 4.2.5 on 2023-11-15 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_uploadedzip_rules'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedzip',
            name='rules',
            field=models.CharField(max_length=255),
        ),
    ]
