# Generated by Django 4.2.5 on 2023-11-15 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_uploadedzip_rules'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedzip',
            name='vulnerablity',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
