# Generated by Django 4.2.5 on 2023-11-15 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_uploadedzip_vulnerablity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedzip',
            name='vulnerablity',
            field=models.CharField(max_length=255),
        ),
    ]
