# Generated by Django 4.2.5 on 2023-11-15 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_uploadedzip_vulnerablity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploadedzip',
            old_name='vulnerablity',
            new_name='vul',
        ),
    ]
